services:
  webserver:
    depends_on:
      - db
    environment:
      MIX_ENV: prod
      PORT: ${PORT}
      DATABASE_URL: postgres://postgres:${DB_PASSWORD}@db/tory
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      OCTOPART_APIKEY: ${OCTOPART_APIKEY}
    image: johnemac36/tory_webserver
    build: webserver
    ports:
      - "${PORT}:${PORT}"
  db:
    build: db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432
networks:
  default:
    name: tory
