services:
  webserver:
    depends_on:
      - db
    environment:
      MIX_ENV: prod
      PORT: ${HTTP_PORT}
      DATABASE_URL: postgres://postgres:${DB_PASSWORD}@db/tory
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      NEXAR_APP_NAME: ${NEXAR_APP_NAME}
      NEXAR_APP_CLIENT_ID: ${NEXAR_APP_CLIENT_ID}
      NEXAR_APP_SECRET_ID: ${NEXAR_APP_SECRET_ID}
    image: johnemac36/tory_webserver
    build: webserver
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
  db:
    build: db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432

networks:
  default:
    name: tory
